config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  Spree::Core::Engine.add_routes do
    resources :payu, only: [:index, :create]
    resources :cookie, only: [:create]
    resources :contact_form, only: [:create]
    resources :payu_notify, only: [:create, :index]

    post 'payment_status', to: "payu#payment_status"
    get 'store_return', to: "payu#store_return"

    get "/terms-of-service", to: "tos#index", as: :tos
    get "/returns", to: "returns#index", as: :returns
    # get "/", to: "under_construction#index"
    # get "home", to: "home#index"
  end

  Spree::Core::Engine.add_routes do
    get '/hero_images', to: 'hero_image#index', as: 'hero_images'
    get '/hero_images/new', to: 'hero_image#new', as: 'new_hero_image'
    get '/hero_images/:id', to: 'hero_image#view', as: 'view_hero_image'
    post '/hero_images', to: 'hero_image#create', as: 'create_hero_image'
    delete '/hero_images/:id', to: 'hero_image#destroy', as: 'delete_hero_image'
  end
end

app/controllers/spree/admin/products_controller.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      helper 'spree/products'

      before_action :load_data, except: :index
      create.before :create_before
      update.before :update_before
      helper_method :clone_object_url

      def show
        session[:return_to] ||= request.referer
        redirect_to action: :edit
      end

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def update
        if params[:product][:taxon_ids].present?
          params[:product][:taxon_ids] = params[:product][:taxon_ids].split(',')
        end
        if params[:product][:option_type_ids].present?
          params[:product][:option_type_ids] = params[:product][:option_type_ids].split(',')
        end
        if params[:product][:sale_price].present?
          @object.master.update!(sale_price: params[:product][:sale_price])
        else
          @object.master.update(sale_price: nil)
        end
        params[:product].delete :sale_price

        invoke_callbacks(:update, :before)
        if @object.update(permitted_resource_params)
          invoke_callbacks(:update, :after)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the product again
          @product.slug = @product.slug_was if @product.slug.blank?
          invoke_callbacks(:update, :fails)
          respond_with(@object)
        end
      end

      def destroy
        @product = Product.friendly.find(params[:id])

        begin
          # TODO: why is @product.destroy raising ActiveRecord::RecordNotDestroyed instead of failing with false result
          if @product.destroy
            flash[:success] = Spree.t('notice_messages.product_deleted')
          else
            flash[:error] = Spree.t('notice_messages.product_not_deleted', error: @product.errors.full_messages.to_sentence)
          end
        rescue ActiveRecord::RecordNotDestroyed => e
          flash[:error] = Spree.t('notice_messages.product_not_deleted', error: e.message)
        end

        respond_with(@product) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      def clone
        @new = @product.duplicate

        if @new.persisted?
          flash[:success] = Spree.t('notice_messages.product_cloned')
          redirect_to edit_admin_product_url(@new)
        else
          flash[:error] = Spree.t('notice_messages.product_not_cloned', error: @new.errors.full_messages.to_sentence)
          redirect_to admin_products_url
        end
      rescue ActiveRecord::RecordInvalid => e
        # Handle error on uniqueness validation on product fields
        flash[:error] = Spree.t('notice_messages.product_not_cloned', error: e.message)
        redirect_to admin_products_url
      end

      def stock
        @variants = @product.variants.includes(*variant_stock_includes)
        @variants = [@product.master] if @variants.empty?
        @stock_locations = StockLocation.accessible_by(current_ability)
        if @stock_locations.empty?
          flash[:error] = Spree.t(:stock_management_requires_a_stock_location)
          redirect_to admin_stock_locations_path
        end
      end

      protected

      def find_resource
        Product.with_deleted.friendly.find(params[:id])
      end

      def location_after_save
        spree.edit_admin_product_url(@product)
      end

      def load_data
        @taxons = Taxon.order(:name)
        @option_types = OptionType.order(:name)
        @tax_categories = TaxCategory.order(:name)
        @shipping_categories = ShippingCategory.order(:name)
      end

      def collection
        return @collection if @collection.present?

        params[:q] ||= {}
        params[:q][:deleted_at_null] ||= '1'
        params[:q][:not_discontinued] ||= '1'

        params[:q][:s] ||= 'name asc'
        @collection = super
        # Don't delete params[:q][:deleted_at_null] here because it is used in view to check the
        # checkbox for 'q[deleted_at_null]'. This also messed with pagination when deleted_at_null is checked.
        if params[:q][:deleted_at_null] == '0'
          @collection = @collection.with_deleted
        end
        # @search needs to be defined as this is passed to search_form_for
        # Temporarily remove params[:q][:deleted_at_null] from params[:q] to ransack products.
        # This is to include all products and not just deleted products.
        @search = @collection.ransack(params[:q].reject { |k, _v| k.to_s == 'deleted_at_null' })
        @collection = @search.result.
                      includes(product_includes).
                      page(params[:page]).
                      per(params[:per_page] || Spree::Config[:admin_products_per_page])
        @collection
      end

      def create_before
        return if params[:product][:prototype_id].blank?

        @prototype = Spree::Prototype.find(params[:product][:prototype_id])
      end

      def update_before
        # note: we only reset the product properties if we're receiving a post
        #       from the form on that tab
        return unless params[:clear_product_properties]

        params[:product] ||= {}
      end

      def product_includes
        [{ variants: [:images], master: [:images, :default_price] }]
      end

      def clone_object_url(resource)
        clone_admin_product_url resource
      end

      private

      def variant_stock_includes
        [:images, stock_items: :stock_location, option_values: :option_type]
      end
    end
  end
end

app/controllers/spree/contact_form_controller.rb
# frozen_string_literal: true

module Spree
  class ContactFormController < Spree::BaseController
    def create
      ContactFormMailer.inquiry_email(
        params["email"],
        params["name"],
        params["company"],
        params["nip"],
        params["message"], 
        ENV['DELIVER_EMAIL']
      ).deliver_now

      redirect_to "#{root_path}#contact-form", flash: { success: "Dziękujemy za kontakt, wrócimy niebawem z odpowiedzią!" }
    end
  end
end

app/controllers/spree/cookie_controller.rb
# frozen_string_literal: true

module Spree
  class CookieController < Spree::BaseController
    def create
      cookies[:cookie] = true
    end
  end
end

app/controllers/spree/hero_image_controller.rb
# Frozen_String_Literal: true

module Spree
	class HeroImageController < Spree::Admin::BaseController
		before_action :set_hero_image, only: %i(view destroy)

		def index
			@hero_images = Spree::HeroImage.select { |x|
				x.image.attached?
			}
		end

		def new
			@hero_image = Spree::HeroImage.new
		end

		def view
		end

		def create
			@hero_image = Spree::HeroImage.create(hero_image_params)

			if @hero_image.save
				redirect_with_notice "Nowy baner został dodany do strony głównej"
			else
				flash.notice = "Nie można załadować tego pliku"
				render 'Nowy'
			end
		end

		def destroy
			@hero_image.destroy
			redirect_with_notice "Zdjęcie zostało usunięte z powodzeniem"
		end

		private
		def hero_image_params
			params.require(:hero_image).permit(:image)
		end

		def redirect_with_notice(message)
			flash.notice = message
			redirect_to hero_images_path
		end

		def set_hero_image
			id = params[:id].to_i

			begin
				@hero_image = Spree::HeroImage.find(id)

			rescue ActiveRecord::RecordNotFound
				redirect_with_notice("Zdjęcie o numerze ID#{id} nie zostało znalezione")

			rescue StandardError
				redirect_with_notice("Ups! Nieznany błąd. Skontaktuj się z twórcą strony")
			end			# Rescue block
		end				# end of set_hero_image definition
	end					# End of HeroImageController
end 					# End of module Spree

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    def index
	    @hero_images = Spree::HeroImage.all.map { |x|
          main_app.url_for(x.image)
      }
    end
  end
end

app/controllers/spree/payu_controller.rb
# frozen_string_literal: true

module Spree
  class PayuController < Spree::BaseController
    def create
      access_token = PayuAccessToken.execute!

      redirect = PayuCreateOrder.execute!(
        params[:order],
        access_token,
        request.remote_ip
      )

      redirect_to redirect
    end

    def store_return
      order = Order.find_by(number: params["order"])

      PayuCheckStatus.execute!(
        order.number,
        PayuAccessToken.execute!
      )

      if order.payment_state == "balance_due"
        redirect_to order_path(order), flash: { success: "Dziękujemy za zamówienie, czekamy na potwierdzenie płatności. Proszę sprawdzić skrzynkę email" }
        ::PayuStatusWorker.perform_async(order.number)
        ::PayuStatusWorker.perform_in(2.minutes, order.number)
        ::PayuStatusWorker.perform_in(10.minutes, order.number)
        ::PayuStatusWorker.perform_in(20.minutes, order.number)

      elsif order.payment_state == "paid"
        redirect_to order_path(order), flash: { success: "Dziękujemy za zamówienie, prosimy o sprawdzenie skrzynki email" }
      elsif order.payment_state == "void"
        redirect_to root_path, flash: { error: "Przykro nam, Twoje zamówienie się nie powiodło, prosimy o kontakt" }
      end
    end

    def payment_status
      order = Order.find_by(number: params["order"])
      begin
      notice = PayuCheckStatus.execute!(
        order.number,
        PayuAccessToken.execute!
      )
      rescue NoMethodError
        notice = "Order not registered on PayU, please consider cancelling it"
      end
      redirect_to request.referer, flash: { notice: notice }
    end
  end
end

app/controllers/spree/returns_controller.rb
class Spree::ReturnsController < Spree::BaseController
    def index; end
end

app/controllers/spree/tos_controller.rb
class Spree::TosController < Spree::BaseController
  def index; end
end

app/helpers/spree/base_helper.rb
module Spree
  module BaseHelper
    def display_original_price(product_or_variant)
      product_or_variant.
        original_price_in(current_currency).
        display_price_including_vat_for(current_price_options).
        to_html
    end

    def sale_percent(original_amount, sale_amount)
      100 - ((sale_amount.amount / original_amount.amount) * 100).round(2)
    end

    def available_countries
      checkout_zone = Spree::Zone.find_by(name: Spree::Config[:checkout_zone])

      countries = if checkout_zone && checkout_zone.kind == 'country'
                    checkout_zone.country_list
                  else
                    Spree::Country.all
                  end

      countries.collect do |country|
        country.name = Spree.t(country.iso, scope: 'country_names', default: country.name)
        country
      end.sort_by { |c| c.name.parameterize }
    end

    def display_price(product_or_variant)
      product_or_variant.
        price_in(current_currency).
        display_price_including_vat_for(current_price_options).
        to_html
    end

    def link_to_tracking(shipment, options = {})
      return unless shipment.tracking && shipment.shipping_method

      options[:target] ||= :blank

      if shipment.tracking_url
        link_to(shipment.tracking, shipment.tracking_url, options)
      else
        content_tag(:span, shipment.tracking)
      end
    end

    def logo(image_path = Spree::Config[:logo], options = {})
      path = spree.respond_to?(:root_path) ? spree.root_path : main_app.root_path

      link_to path, 'aria-label': current_store.name, method: options[:method] do
        image_tag image_path, alt: current_store.name, title: current_store.name
      end
    end

    def meta_data
      object = instance_variable_get('@' + controller_name.singularize)
      meta = {}

      if object.is_a? ApplicationRecord
        meta[:keywords] = object.meta_keywords if object[:meta_keywords].present?
        meta[:description] = object.meta_description if object[:meta_description].present?
      end

      if meta[:description].blank? && object.is_a?(Spree::Product)
        meta[:description] = truncate(strip_tags(object.description), length: 160, separator: ' ')
      end

      if meta[:keywords].blank? || meta[:description].blank?
        if object && object[:name].present?
          meta.reverse_merge!(keywords: [object.name, current_store.meta_keywords].reject(&:blank?).join(', '),
                              description: [object.name, current_store.meta_description].reject(&:blank?).join(', '))
        else
          meta.reverse_merge!(keywords: (current_store.meta_keywords || current_store.seo_title),
                              description: (current_store.meta_description || current_store.seo_title))
        end
      end
      meta
    end

    def meta_image_url_path
      object = instance_variable_get('@' + controller_name.singularize)
      return unless object.is_a?(Spree::Product)

      image = default_image_for_product_or_variant(object)
      image&.attachment.present? ? main_app.url_for(image.attachment) : asset_path(Spree::Config[:logo])
    end

    def meta_image_data_tag
      tag('meta', property: 'og:image', content: meta_image_url_path) if meta_image_url_path
    end

    def meta_data_tags
      meta_data.map do |name, content|
        tag('meta', name: name, content: content) unless name.nil? || content.nil?
      end.join("\n")
    end

    def method_missing(method_name, *args, &block)
      if image_style = image_style_from_method_name(method_name)
        define_image_method(image_style)
        send(method_name, *args)
      else
        super
      end
    end

    def pretty_time(time)
      return '' if time.blank?

      [I18n.l(time.to_date, format: :long), time.strftime('%l:%M %p')].join(' ')
    end

    def seo_url(taxon, options = nil)
      spree.nested_taxons_path(taxon.permalink, options)
    end

    def frontend_available?
      Spree::Core::Engine.frontend_available?
    end

    # we should always try to render image of the default variant
    # same as it's done on PDP
    def default_image_for_product(product)
      if product.default_variant.images.any?
        product.default_variant.images.first
      elsif product.variant_images.any?
        product.variant_images.first
      end
    end

    def display_compare_at_price(product_or_variant)
      product_or_variant.
        price_in(current_currency).
        display_compare_at_price_including_vat_for(current_price_options).
        to_html
    end

    def default_image_for_product_or_variant(product_or_variant)
      Rails.cache.fetch("spree/default-image/#{product_or_variant.cache_key_with_version}") do
        if product_or_variant.is_a?(Spree::Product)
          default_image_for_product(product_or_variant)
        elsif product_or_variant.is_a?(Spree::Variant)
          if product_or_variant.images.any?
            product_or_variant.images.first
          else
            default_image_for_product(product_or_variant.product)
          end
        end
      end
    end

    def base_cache_key
      [I18n.locale, current_currency]
    end

    private

    def create_product_image_tag(image, product, options, style)
      options[:alt] = image.alt.blank? ? product.name : image.alt
      image_tag main_app.url_for(image.url(style)), options
    end

    def define_image_method(style)
      self.class.send :define_method, "#{style}_image" do |product, *options|
        options = options.first || {}
        options[:alt] ||= product.name
        image_path = default_image_for_product_or_variant(product)
        if image_path.present?
          create_product_image_tag image_path, product, options, style
        else
          image_tag "noimage/#{style}.png", options
        end
      end
    end

    # Returns style of image or nil
    def image_style_from_method_name(method_name)
      if method_name.to_s.match(/_image$/) && style = method_name.to_s.sub(/_image$/, '')
        style if style.in? Spree::Image.styles.with_indifferent_access
      end
    end
  end
end

app/views/spree/hero_image/index.html.erb
<div class="row align-items-center  border-bottom">
    <h1 class="contextual-title px-0 mb-0 col">
        Nowe zdjęcie
    </h1>

    <div class="page-actions pl-0 pr-0" data-hook="toolbar">
      <%= link_to new_hero_image_path, class: 'btn btn-success' do %>
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16px" height="16px" viewBox="0 0 512 512" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;" class="icon-add icon icon-add.svg">
          <g transform="matrix(-8.69966,-8.69966,-8.69966,8.69966,481.449,256.527)">
              <path d="M14.061,12.927L24.78,23.646C25.073,23.939 25.073,24.414 24.78,24.707C24.487,25 24.013,25 23.72,24.707L13,13.987L2.28,24.707C1.987,25 1.513,25 1.22,24.707C0.927,24.414 0.927,23.939 1.22,23.646L11.939,12.927L1.22,2.207C0.927,1.914 0.927,1.439 1.22,1.146C1.366,1 1.558,0.927 1.75,0.927C1.942,0.927 2.134,1 2.28,1.146L13,11.866L23.72,1.146C23.866,1 24.058,0.927 24.25,0.927C24.442,0.927 24.634,1 24.78,1.146C25.073,1.439 25.073,1.914 24.78,2.207L14.061,12.927Z" style="fill-rule:nonzero;stroke:currentColor;stroke-width:2.76px;"></path>
          </g>
        </svg>
        <%= I18n.t("new_image", scope: ['spree', 'admin']) %>
      <% end %>
    </div>
</div>

<% @hero_images.each_with_index do |f, i| %>
  <div class="row pt-2">
      <div class="col-md-1" >
        <span class="truncate-30px"><%= sprintf "%02d", i + 1 %>.</span>
      </div>

      <div class="col-md-9">
        <div class="w-20">
          <%= image_tag main_app.url_for(f.image), class: 'hero-image' %>
        </div>
        <span class="truncate-70"><%= f.image.filename %></span>
      </div>

      <div class="col-md-2">
          <%= link_to view_hero_image_path(f), class: "btn-icon" do %>
            <%= image_tag 'icons/eye.svg', class: "icon-16px" %>
          <% end %>

            <%= link_to delete_hero_image_path(f),
              method: :delete, class: "btn-icon", data: { confirm: 'Are you sure?' } do
            %>
              <%= image_tag 'icons/remove.svg', class: "icon-16px" %>
            <% end %>
          </a>
      </div>
    </div>
<% end %>

<style>
  .hero-image {
  	width: 50px;
  	height: 50px;
    display: inline-block;
  }

  .btn-icon {
    margin-right: 4px;
    border-radius: 4px;
    opacity: 0.75;
    transition: all 0.125s ease;
    text-decoration: none;
  }

  .btn-icon:last-child {
    margin-right: 0;
  }

  .btn-icon:hover {
    text-decoration: none;
    filter: drop-shadow(3px 3px 2px #0006);
  }

  .icon-16px {
    width: 16px;
    height: 16px;
  }

  .truncate-30px, .truncate-70 {
    display: inline-block;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .truncate-30px {
      width: 30px;
  }

  .w-20 {
    display: inline-block;
    width: 20%;
  }

  .truncate-70 {
    width: 70%;
  }
</style>

app/views/spree/hero_image/new.html.erb
<div class="row align-items-center  border-bottom">
  <%= link_to hero_images_path do %>
    <%= image_tag 'icons/left_arrow.svg', width: '24px', class: 'mr-2 icon-hover'%>
  <% end %>

  <h1 class="contextual-title px-0 mb-0 col">
      <%= I18n.t("new_image", scope: ['spree', 'admin']) %>
  </h1>
</div>

<%= form_for(@hero_image, url: hero_images_path) do |f| %>
  <% if @hero_image.image.attached? %>
    <%= image_tag main_app.url_for(@hero_image.image), class: 'image-90 m-2' %>
  <% end %>

  <div class="mt-2">
    <%= f.label :image %>
  </div>

  <div class="mt-2">
    <%= f.file_field :image %>
  </div>

  <div style="display: block;text-align: center;padding-top: 8vh">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

<style>
  .icon-hover {
    transition: all 0.25s ease;
  }

  .icon-hover:hover {
    cursor: pointer;
    filter: brightness(1.125);
  }
</style>

app/views/spree/hero_image/view.html.erb
<div class="row align-items-center  border-bottom">
  <%= link_to hero_images_path do %>
    <%= image_tag 'icons/left_arrow.svg', width: '24px', class: 'mr-2 icon-hover'%>
  <% end %>

  <h1 class="contextual-title px-0 mb-0 col">
      <%= I18n.t("view_image", scope: ['spree', 'admin']) %>
  </h1>
</div>

<% if @hero_image.image.attached? %>
  <%= image_tag main_app.url_for(@hero_image.image), class: 'image-90 m-2' %>
<% end %>

<style>
  .image-90 {
    width: 90%;
    display: block;
    margin: auto auto;
  }

  .icon-hover {
    transition: all 0.25s ease;
  }

  .icon-hover:hover {
    cursor: pointer;
    filter: brightness(1.125);
  }
</style>